### ISSUE TITLE
sagamap run error

### ISSUE THREAD

**Issue by wfcdkeys** [karorogunso/SagaECO#11]
please help
![TJDL{C((D3B)LQCQZ`%WT 2](https://user-images.githubusercontent.com/85296231/147376134-a89f92f1-2681-4743-af0d-b9c88a905f00.png)
![CNC}CJZ~5@9LMFNG P6FJ5](https://user-images.githubusercontent.com/85296231/147376137-4d2e3ae8-3ec4-41f5-afb1-088c6416c5eb.png)

**Comment by wfcdkeys** [comment]
I have fixed some problem, Added the database, but I still can't in game map,I can create roles and role interface previews,When I click on the start of the role selection interface, it will be black and disconnected. And there are no error information for 3 DOS windows.  may be a problem that the client does not match, I still want you to make a detailed tutorial or Give a client configuration method. Forgive my English is not good。
![C6G7LPT2ZW9V35$J@QLZ B](https://user-images.githubusercontent.com/85296231/147431384-d8b3bb8e-5175-4b0f-bb36-285f221c8543.png)
![B6~3TF W8%$UXUA_AJG37PY](https://user-images.githubusercontent.com/85296231/147431392-8b12381e-12ba-41a4-91eb-37d85c60f703.png)

**Comment by shinjangww** [comment]
Excuse me, can I ask what program you use to open your server and mysql?

**Comment by shinjangww** [comment]
I had this problem when I opened the saga900 server, I changed the ciln so I can access it.

**Comment by shinjangww** [comment]
> I have fixed some problem, Added the database, but I still can't in game map,I can create roles and role interface previews,When I click on the start of the role selection interface, it will be black and disconnected. And there are no error information for 3 DOS windows.  may be a problem that the client does not match, I still want you to make a detailed tutorial or Give a client configuration method. Forgive my English is not good。
> 
> ![C6G7LPT2ZW9V35$J@QLZ B](https://user-images.githubusercontent.com/85296231/147431384-d8b3bb8e-5175-4b0f-bb36-285f221c8543.png)
> 
> ![B6~3TF W8%$UXUA_AJG37PY](https://user-images.githubusercontent.com/85296231/147431392-8b12381e-12ba-41a4-91eb-37d85c60f703.png)
> 
> 
> 
> Try this client game.https://drive.google.com/file/d/12HlxevA2tgDLiKXF3950ZZUb7S9SfeDL/view

Excuse me, can I ask what program you use to open your server and mysql?

**Comment by tankoko91** [comment]
Hi... Which saga version client you are using? Saga 10 or 17?
