### ISSUE TITLE
Working on New SagaECo I found.

### ISSUE THREAD

**Issue by karorogunso** [karorogunso/SagaECO#6]

**Comment by Nizaki** [comment]
@karorogunso  can you share any information about new sagaeco ?

**Comment by karorogunso** [comment]
@Nizaki check a new commit.

**Comment by karorogunso** [comment]
@Nizaki  check a new commit. Hope you enjoy it.

**Comment by Nizaki** [comment]
สุดยอดไปเลยครับ ว่าแต่อันนี้เป็นไฟล์ของเซิฟใหนหรอครับ
